### ISSUE TITLE
angular-cli project can't use angular-starter-library

### ISSUE THREAD

**Issue by chaosmonster** [manekinekko/angular-library-starter#4]
How to reproduce

* set up a new project using `angular-cli`
* run `ng serve` works 
* run `ng -serve -aot` works
* follow these [steps](https://github.com/manekinekko/angular-library-starter#using-you-library-in-another-project) to include in the new project
* run `ng serve` works 
* run `ng -serve -aot`fails because of angular-starter-library

what am I missing?

**Comment by manekinekko** [comment]
@chaosmonster this starter is not compatible with the CLI.

**Comment by chaosmonster** [comment]
That explains my other issue with module.id ;) 
I will close this issue
