### ISSUE TITLE
Add custom definition file

### ISSUE THREAD

**Issue by ArielGueta** [manekinekko/angular-library-starter#5]
I'm wondering, if I need to include custom definition file for my library, for example, a third party plugin that I need to create typings for, how can I ship this file with the library? 

For example `third-party-lib.d.ts`.

**Comment by manekinekko** [comment]
hi @ArielGueta I just added a [custom typings](https://github.com/manekinekko/angular-library-starter/blob/master/src/custom-typings.d.ts) file for this. Check it out. Let me know if that makes sens for you.

**Comment by ArielGueta** [comment]
This is awesome! Thank you very much!
